services:
  fresh-trash-rabbitmq:
    container_name: fresh-trash-rabbitmq
    build:
      dockerfile: Dockerfile
      context: ./rabbitmq
    image: fresh-trash-rabbitmq:0.1
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS}
    ports:
      - "15672:15672"
      - "61613:61613"
      - "5672:5672"
    networks:
      - docker-redis

networks:
  docker-redis:
    driver: bridge
