version: "1"
services:
  fresh-trash-rabbitmq:
    container_name: fresh-trash-rabbitmq
    build:
      dockerfile: Dockerfile
      context: ./rabbitmq
    image: rabbitmq:3
    ports:
      - "5672:5672"
    networks:
      - docker-redis

networks:
  docker-redis:
    driver: bridge