services:
  fresh-trash-rabbitmq:
    container_name: fresh-trash-rabbitmq
    build:
      dockerfile: Dockerfile
      context: ./rabbitmq
    image: fresh-trash-rabbitmq:0.1
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS}
    ports:
      - "15672:15672"
      - "61613:61613"
      - "5672:5672"
    networks:
      - docker_app
  fresh-trash-nginx:
    container_name: fresh-trash-nginx
    image: fresh-trash-nginx:0.1
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker_app

networks:
  docker_app:
    driver: bridge
