version: "1"
services:
  fresh-trash-rabbitmq:
    container_name: fresh-trash-rabbitmq
    build:
      dockerfile: Dockerfile
      context: ./rabbitmq
    image: fresh-trash-rabbitmq:0.1
    ports:
      - "15672:15672"
      - "61613:61613"
      - "5672:5672"
    networks:
      - docker-redis

networks:
  docker-redis:
    driver: bridge
