spring:
  config.activate.on-profile: common
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        metadata_builder_contributor: freshtrash.freshtrashbackend.config.JSONMetadataBuilderContributor
  rabbitmq:
    port: ${AMQP_PORT}
    host: ${AMQP_HOST}
    username: ${AMQP_USER}
    password: ${AMQP_PASS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}