spring:
  profiles:
    active: local # default
    group:
      local:
        - common
        - amqp
        - file
        - mail
        - security
      integration_test:
        - common
        - amqp
        - file
        - mail
        - security
      test:
        - file
        - mail
        - security
      prod:
        - common
        - amqp
        - file
        - mail
        - security

---

spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
  devtools.livereload:
    enabled: true
    port: 35730

---

spring:
  config.activate.on-profile: integration_test
  jpa:
    hibernate:
      ddl-auto: validate
  devtools.livereload:
    enabled: true
    port: 35730
logging:
  level:
    org.springframework.transaction: debug
    org.springframework.orm.jpa: debug
    freshtrash.freshtrashbackend: debug

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql.init.mode: always

---

spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
