spring:
  config.activate.on-profile: amqp
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USER}
    password: ${AMQP_PASS}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual # default: auto
