spring:
  config.activate.on-profile: file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
local-file:
  absolute-path: ${LOCAL_FILE_ABS_PATH} # 파일 저장 경로
aws.s3:
  bucket-name: ${S3_BUCKET_NAME}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
