spring:
  config.activate.on-profile: common
  web:
    locale: ko_KR
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        metadata_builder_contributor: freshtrash.freshtrashbackend.config.JSONMetadataBuilderContributor
        jdbc:
          batch_size: 10
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
