version: "3.8"
services:
  fresh-trash-database:
    container_name: fresh-trash-database
    build:
      dockerfile: Dockerfile
      context: ./mariadb
    image: mariadb:10
    environment:
      - MARIADB_DATABASE=fresh_trash
      - MARIADB_USER=${SPRING_DATASOURCE_USER}
      - MARIADB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_ROOT_PASSWORD}
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
    networks:
      - docker_app
  fresh-trash-redis:
    container_name: fresh-trash-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - docker_app

networks:
  docker_app:
    driver: bridge


