upstream backend {
    server host.docker.internal:8080;
    keepalive_timeout 0;
}

upstream backendAlive {
    server host.docker.internal:8080;
    keepalive 16;
    keepalive_timeout 30m;
}

upstream prometheus {
    server host.docker.internal:8090;
    keepalive_timeout 0;
}

upstream recsys {
    server host.docker.internal:9080;
    keepalive_timeout 0;
}

log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

server {
    server_name localhost;
    listen 80;
    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log upstream_time;

    location ~ notis/subscribe$ {
        # preflight response
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:5173';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
            add_header 'Access-Control-Allow-Credentials' 'true';
            return 204;
        }

        proxy_pass http://backendAlive$request_uri;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        proxy_read_timeout 30m;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location ~ /(api|imgs|oauth2|login) {
        # preflight response
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:5173';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
            add_header 'Access-Control-Allow-Credentials' 'true';
            return 204;
        }

        rewrite ^/(.*)$ /$1 break;

        proxy_pass http://backend/$1$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /chat-ws {
        proxy_pass http://backendAlive/chat-ws;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_http_version 1.1;
        proxy_read_timeout 30m;
        proxy_send_timeout 30m;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

    location /actuator/prometheus {
        proxy_pass http://prometheus$request_uri;
    }

    location ~ /rec-sys {
        # preflight response
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:5173';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
            add_header 'Access-Control-Allow-Credentials' 'true';
            return 204;
        }

        proxy_pass http://recsys$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Credentials' 'true';
    }
}
