insert into members(email, password, rating, nickname, address, file_name, login_type, user_role, account_status,
                    created_at, modified_at, flag_count)
values ('abc@never.com', '$2a$10$ZskRs64yZZU9g6blmNdZte7FO6KaMduwlZhk7YkxJX2ZwYLSrPfA.', 5, 'abc',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        'test.jpg', 'EMAIL', 'USER', 'ACTIVE', now(), null, 0),
       ('def@never.com', '$2a$10$6UF8CDeP2A7ACjMVE/cpS.DlgRw/ZRA0NuHFnpziEpbasOhS6EGq.', 4, 'def',
        null, null, 'EMAIL', 'USER', 'ACTIVE', now(), null, 0),
       ('user123@never.com', '$2a$10$6UF8CDeP2A7ACjMVE/cpS.DlgRw/ZRA0NuHFnpziEpbasOhS6EGq.', 3, 'user123',
        null, null, 'EMAIL', 'USER', 'ACTIVE', now(), null, 0),
       ('user456@never.com', '$2a$10$6UF8CDeP2A7ACjMVE/cpS.DlgRw/ZRA0NuHFnpziEpbasOhS6EGq.', 2, 'user456',
        null, null, 'EMAIL', 'USER', 'ACTIVE', now(), null, 0),
       ('user777@never.com', '$2a$10$6UF8CDeP2A7ACjMVE/cpS.DlgRw/ZRA0NuHFnpziEpbasOhS6EGq.', 2, 'user777',
        null, null, 'EMAIL', 'USER', 'ACTIVE', now(), null, 0),
       ('blackUser@gmail.com', '$2a$10$6UF8CDeP2A7ACjMVE/cpS.DlgRw/ZRA0NuHFnpziEpbasOhS6EGq.', 2, 'blackUser',
        null, null, 'EMAIL', 'BLACK_USER', 'ACTIVE', now(), null, 10);


insert into products(member_id, title, content, product_price, like_count, view_count, file_name, product_category,
                     product_status,
                     sell_status, address, created_at, modified_at, product_deal_at)
values (1, '청바지', '청바지팝니다.', 0, 1, 0, '1.jpg', 'CLOTHING', 'GOOD', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (2, '양배추', '양배추팝니다.', 1000, 2, 3, '2.jpg', 'HEALTH', 'GOOD', 'ONGOING',
        json_object('zipcode', '16255', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (3, '데님셔츠', '데님셔츠팝니다.', 0, 3, 4, '3.jpg', 'CLOTHING', 'GOOD', 'ONGOING',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (4, '방울토마토', '방울토마토팝니다.', 0, 10, 5, '4.jpg', 'HEALTH', 'GOOD', 'ONGOING',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (1, '꽃병 세트', '꽃병 세트팝니다.', 500, 1, 110, '5.jpg', 'FURNITURE_DECOR', 'BEST', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (2, '책상, 의자', '책상과 의자 같이 팝니다.', 1000, 2, 3, '6.jpg', 'FURNITURE_DECOR', 'GOOD', 'CLOSE',
        json_object('zipcode', '16255', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (3, '운동화', '운동화팝니다.', 0, 334, 433, '7.jpg', 'SPORTS', 'BEST', 'CLOSE',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (4, '치마', '치마팝니다.', 0, 110, 51, '8.jpg', 'CLOTHING', 'GOOD', 'CLOSE',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (2, '침대', '침대팝니다.', 1000, 2, 3, '9.jpg', 'FURNITURE_DECOR', 'GOOD', 'CLOSE',
        json_object('zipcode', '16255', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (3, '2KG 덤벨', '2KG 덤벨 2개 팝니다.', 0, 334, 433, '10.jpg', 'SPORTS', 'BEST', 'CLOSE',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (4, '샌들', '샌들팝니다.', 0, 110, 51, '11.jpg', 'CLOTHING', 'GOOD', 'CLOSE',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (2, '좌식 책상', '침대에서 사용하기 좋은 좌식 책상팝니다.', 1000, 2, 3, '12.jpg', 'FURNITURE_DECOR', 'GOOD', 'CLOSE',
        json_object('zipcode', '16255', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (3, '줄넘기', '줄넘기팝니다.', 0, 334, 433, '13.jpg', 'SPORTS', 'BEST', 'CLOSE',
        json_object('zipcode', '16666', 'state', '경기도', 'city', '수원시', 'district', '팔달구', 'detail', '창룡대로'),
        now(), null, null),
       (1, '킹 사이즈 침대팝니다.', '킹 사이즈 침대팝니다.', 500, 1, 110, '14.jpg', 'FURNITURE_DECOR', 'WORST', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '의자', '의자팝니다.', 0, 23, 234, '15.jpg', 'FURNITURE_DECOR', 'GOOD', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '나무 의자', '의자팝니다.', 2500, 578, 345, '16.jpg', 'FURNITURE_DECOR', 'GOOD', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '테이블', '테이블팝니다.', 3000, 2345, 34, '17.jpg', 'FURNITURE_DECOR', 'NORMAL', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '야외 의자', '야외용 의자팝니다.', 0, 34, 56, '18.jpg', 'FURNITURE_DECOR', 'NORMAL', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '화분', '화분팝니다.', 500, 456, 90, '19.jpg', 'PLANT_SUPPLIES', 'WORST', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '의자', '의자팝니다.', 500, 456, 90, '20.jpg', 'FURNITURE_DECOR', 'BEST', 'CLOSE',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '소파', '소파팝니다.', 500, 43, 90, '21.jpg', 'FURNITURE_DECOR', 'BEST', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '의자', '의자팝니다.', 500, 456, 789, '22.jpg', 'FURNITURE_DECOR', 'GOOD', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '옷장', '옷장팝니다.', 500, 23, 90, '23.jpg', 'FURNITURE_DECOR', 'GOOD', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '소파', '소파팝니다.', 0, 456, 56, '24.jpg', 'FURNITURE_DECOR', 'NORMAL', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '화분', '화분팝니다.', 500, 234, 90, '25.jpg', 'PLANT_SUPPLIES', 'BEST', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '스탠드 옷걸이', '스탠드 옷걸이팝니다.', 0, 456, 456, '26.jpg', 'FURNITURE_DECOR', 'WORST', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null),
       (1, '소파', '소파팝니다.', 500, 456, 90, '27.jpg', 'FURNITURE_DECOR', 'NORMAL', 'ONGOING',
        json_object('zipcode', '12345', 'state', 'state', 'city', 'city', 'district', 'district', 'detail', 'detail'),
        now(), null, null);


insert into product_likes(member_id, product_id, created_at)
values (1, 1, now()),
       (1, 2, now()),
       (1, 3, now()),
       (1, 4, now()),
       (1, 5, now()),
       (1, 6, now()),
       (1, 7, now()),
       (1, 8, now()),
       (2, 4, now()),
       (3, 5, now()),
       (4, 6, now()),
       (2, 7, now()),
       (3, 8, now());

INSERT INTO chat_rooms(product_id, seller_id, buyer_id, sell_status, open_or_close, created_at)
VALUES (1, 1, 2, 'ONGOING', 1, now()),
       (1, 1, 3, 'CLOSE', 1, now()),
       (1, 1, 4, 'ONGOING', 1, now());


INSERT INTO chat_messages(chat_room_id, member_id, message, created_at)
VALUES (1, 1, '첫 번째 메세지입니다.', now());

insert into product_deal_logs(product_id, seller_id, buyer_id, created_at)
values (5, 1, 2, now()),
       (6, 2, 1, now()),
       (7, 3, 1, now()),
       (8, 4, 1, now()),
       (9, 2, 1, now()),
       (10, 3, 1, now()),
       (11, 4, 1, now()),
       (12, 2, 1, now()),
       (13, 3, 1, now()),
       (14, 1, 2, now()),
       (15, 1, 2, now()),
       (16, 1, 2, now()),
       (17, 1, 2, now()),
       (18, 1, 2, now()),
       (19, 1, 2, now()),
       (20, 1, 2, now());

insert into alarms(member_id, alarm_type, alarm_args, message, created_at, read_at, deleted_at)
values (1, 'CANCEL_BOOKING', json_object('fromMemberId', 2, 'targetId', 1), '🛒def님이 판매중으로 변경하였습니다.', now(), null, null),
       (1, 'CANCEL_BOOKING', json_object('fromMemberId', 3, 'targetId', 2), '🛒user123님이 판매중으로 변경하였습니다.', now(), null, null),
       (1, 'REQUEST_BOOKING', json_object('fromMemberId', 3, 'targetId', 1), '🛒user123님이 예약중으로 변경하였습니다.', now(), null, null),
       (1, 'REQUEST_BOOKING', json_object('fromMemberId', 3, 'targetId', 1), '🛒user123님이 예약중으로 변경하였습니다.', now(), null, null),
       (1, 'COMPLETE_TRANSACTION', json_object('fromMemberId', 3, 'targetId', 1), '✅애물단지 거래가 완료되었습니다.', now(), null, null),
       (1, 'COMPLETE_TRANSACTION', json_object('fromMemberId', 3, 'targetId', 1), '✅애물단지 거래가 완료되었습니다.', now(), null, null),
       (1, 'REQUEST_REVIEW', json_object('fromMemberId', 2, 'targetId', 2), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null, null),
       (1, 'REQUEST_REVIEW', json_object('fromMemberId', 3, 'targetId', 3), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null, null),
       (1, 'REQUEST_REVIEW', json_object('fromMemberId', 4, 'targetId', 4), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null,
        null),
       (1, 'REQUEST_REVIEW', json_object('fromMemberId', 5, 'targetId', 5), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null,
        null),
       (1, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🌫️경매 [남성 정장 자켓과 여성 드레스]가 입찰된 내역이 없습니다.', now(), null,
        null),
       (1, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🎉경매 [남성 정장 자켓과 여성 드레스]가 낙찰되었습니다.', now(), null,
        null),
       (1, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🎉축하합니다! 경매 [남성 정장 자켓과 여성 드레스]가 낙찰되었습니다. 이 알림 메시지를 클릭하여 결제 페이지로 이동해 결제를 진행해주세요. 24시간 이내에 결제를 완료해주세요.', now(), null,
        null),
       (1, 'CANCEL_AUCTION', json_object('fromMemberId', 3, 'targetId', 1), '❌경매 [유아 의류]가 취소되었습니다.', now(), null, null),
       (1, 'CANCEL_AUCTION', json_object('fromMemberId', 4, 'targetId', 4), '❌경매 [농구공]가 취소되었습니다.', now(), null, null),
       (1, 'PAY', json_object('fromMemberId', 4, 'targetId', 4), '💳경매 [농구공] 결제가 완료되었습니다.', now(), null, null),
       (1, 'PAY', json_object('fromMemberId', 4, 'targetId', 4), '💳경매 [농구공] 상품 결제가 완료되었습니다. user456님에게 상품을 배송해주세요.', now(), null, null),
       (1, 'NOT_PAY', json_object('fromMemberId', 4, 'targetId', 4), '⚠️user456님이 경매 [농구공] 상품을 24시간 이내에 결제하지않아 해당 경매 낙찰을 취소합니다.', now(), null, null),
       (1, 'NOT_PAY', json_object('fromMemberId', 4, 'targetId', 4), '⚠️경매 [농구공]의 결제가 완료되지 않았습니다. 24시간 이내에 결제하지않아 경매 낙찰을 취소합니다.', now(), null, null),
       (1, 'RECEIVE', json_object('fromMemberId', 4, 'targetId', 4), '📦작성된 상품 리뷰가 있습니다.', now(), null, null),
       (1, 'RECEIVE', json_object('fromMemberId', 4, 'targetId', 4), '📦작성된 상품 리뷰가 있습니다.', now(), null, null),
       (1, 'FLAG', json_object('fromMemberId', 2, 'targetId', 1),
        '🚩9번 경고를 받으셨습니다. 경고가 10번 누적되면 서비스를 이용하실 수 없습니다.', now(), null, null),
       (1, 'FLAG', json_object('fromMemberId', 3, 'targetId', 2),
        '🚩경고가 10번 누적되어 더이상 서비스를 이용하실 수 없습니다.', now(), null, null),
       (2, 'CANCEL_BOOKING', json_object('fromMemberId', 2, 'targetId', 1), '🛒def님이 판매중으로 변경하였습니다.', now(), null, null),
       (2, 'CANCEL_BOOKING', json_object('fromMemberId', 3, 'targetId', 2), '🛒user123님이 판매중으로 변경하였습니다.', now(), null, null),
       (2, 'REQUEST_BOOKING', json_object('fromMemberId', 3, 'targetId', 1), '🛒user123님이 예약중으로 변경하였습니다.', now(), null, null),
       (2, 'REQUEST_BOOKING', json_object('fromMemberId', 3, 'targetId', 1), '🛒user123님이 예약중으로 변경하였습니다.', now(), null, null),
       (2, 'COMPLETE_TRANSACTION', json_object('fromMemberId', 3, 'targetId', 1), '✅애물단지 거래가 완료되었습니다.', now(), null, null),
       (2, 'COMPLETE_TRANSACTION', json_object('fromMemberId', 3, 'targetId', 1), '✅애물단지 거래가 완료되었습니다.', now(), null, null),
       (2, 'REQUEST_REVIEW', json_object('fromMemberId', 1, 'targetId', 1), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null, null),
       (2, 'REQUEST_REVIEW', json_object('fromMemberId', 3, 'targetId', 3), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null, null),
       (2, 'REQUEST_REVIEW', json_object('fromMemberId', 4, 'targetId', 4), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null,
        null),
       (2, 'REQUEST_REVIEW', json_object('fromMemberId', 5, 'targetId', 5), '✅애물단지 거래가 완료되었습니다. 이 알림 메시지를 클릭해서 평점을 남겨주세요.', now(), null,
        null),
       (2, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🌫️경매 [남성 정장 자켓과 여성 드레스]가 입찰된 내역이 없습니다.', now(), null,
        null),
       (2, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🎉경매 [남성 정장 자켓과 여성 드레스]가 낙찰되었습니다.', now(), null,
        null),
       (2, 'BIDDING', json_object('fromMemberId', 3, 'targetId', 5), '🎉축하합니다! 경매 [남성 정장 자켓과 여성 드레스]가 낙찰되었습니다. 이 알림 메시지를 클릭하여 결제 페이지로 이동해 결제를 진행해주세요. 24시간 이내에 결제를 완료해주세요.', now(), now(),
        null),
       (2, 'CANCEL_AUCTION', json_object('fromMemberId', 3, 'targetId', 1), '❌경매 [유아 의류]가 취소되었습니다.', now(), null, null),
       (2, 'CANCEL_AUCTION', json_object('fromMemberId', 4, 'targetId', 4), '❌경매 [농구공]가 취소되었습니다.', now(), null, null),
       (2, 'PAY', json_object('fromMemberId', 4, 'targetId', 4), '💳경매 [농구공] 결제가 완료되었습니다.', now(), null, null),
       (2, 'PAY', json_object('fromMemberId', 4, 'targetId', 4), '💳경매 [농구공] 상품 결제가 완료되었습니다. %s 님에게 상품을 배송해주세요.', now(), null, null),
       (2, 'NOT_PAY', json_object('fromMemberId', 4, 'targetId', 4), '⚠️user456님이 경매 [농구공] 상품을 24시간 이내에 결제하지않아 해당 경매 낙찰을 취소합니다.', now(), null, null),
       (2, 'NOT_PAY', json_object('fromMemberId', 4, 'targetId', 4), '⚠️경매 [농구공]의 결제가 완료되지 않았습니다. 24시간 이내에 결제하지않아 경매 낙찰을 취소합니다.', now(), null, null),
       (2, 'RECEIVE', json_object('fromMemberId', 4, 'targetId', 4), '📦작성된 상품 리뷰가 있습니다.', now(), null, null),
       (2, 'RECEIVE', json_object('fromMemberId', 4, 'targetId', 4), '📦작성된 상품 리뷰가 있습니다.', now(), null, null),
       (2, 'FLAG', json_object('fromMemberId', 2, 'targetId', 1),
        '🚩9번 경고를 받으셨습니다. 경고가 10번 누적되면 서비스를 이용하실 수 없습니다.', now(), null, null),
       (2, 'FLAG', json_object('fromMemberId', 3, 'targetId', 2),
        '🚩경고가 10번 누적되어 더이상 서비스를 이용하실 수 없습니다.', now(), null, null);

insert into auctions(member_id, file_name, title, content, product_category, product_status, auction_status, final_bid,
                     view_count, started_at, ended_at, created_at)
values (1, 'auction1.jpg', '유아 의류', '5세 유아 의류팝니다.', 'CLOTHING', 'GOOD', 'ONGOING', 1000, 1, now(),
        date_add(now(), interval 1 month), now()),
       (2, 'auction2.jpg', '아몬드', '아몬드팝니다.', 'HEALTH', 'GOOD', 'CLOSE', 1000, 3, now(),
        date_add(now(), interval 1 month), now()),
       (3, 'auction3.jpg', '축구공', '축구공팝니다.', 'SPORTS', 'GOOD', 'CLOSE', 3000, 5, now(),
        date_add(now(), interval 1 month), now()),
       (4, 'auction4.jpg', '농구공', '농구공팝니다.', 'SPORTS', 'GOOD', 'CLOSE', 3000, 6, now(), now(), now()),
       (5, 'auction5.jpg', '남성 정장 지켓과 여성 드레스', '남성 정장 자켓과 여성 드레스팝니다.', 'CLOTHING', 'BEST', 'CLOSE', 3000, 7, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction6.jpg', '여성 코디 세트', '여름용 여성 코디 세트팝니다.', 'CLOTHING', 'GOOD', 'ONGOING', 4000, 8, now(),
        date_add(now(), interval 1 month), now()),
       (2, 'auction7.jpg', '장갑', '장갑팝니다.', 'CLOTHING', 'BEST', 'CLOSE', 5000, 9, now(),
        date_add(now(), interval 1 month), now()),
       (3, 'auction8.jpg', '보터햇', '여성용 보터햇팝니다.', 'CLOTHING', 'GOOD', 'CLOSE', 6000, 10, now(),
        date_add(now(), interval 1 month), now()),
       (4, 'auction9.jpg', '패딩 4벌', '패딩 4벌 팝니다.', 'CLOTHING', 'GOOD', 'CLOSE', 7000, 11, now(),
        date_add(now(), interval 1 month), now()),
       (4, 'auction10.jpg', '장갑', '장갑팝니다.', 'CLOTHING', 'GOOD', 'CLOSE', 77000, 111, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction11.jpg', '후드티', '스몰사이즈 후드티팝니다.', 'CLOTHING', 'GOOD', 'ONGOING', 8000, 12, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction12.jpg', '모자', '모자팝니다.', 'CLOTHING', 'BEST', 'ONGOING', 9000, 13, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction13.jpg', '양말', '양말팝니다.', 'CLOTHING', 'GOOD', 'ONGOING', 10000, 14, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction14.jpg', '줄무늬 양말', '양말팝니다.', 'CLOTHING', 'NORMAL', 'ONGOING', 11000, 15, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction15.jpg', 'title14', 'content14', 'CLOTHING', 'NORMAL', 'ONGOING', 12000, 16, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction16.jpg', 'title15', 'content15', 'CLOTHING', 'WORST', 'ONGOING', 13000, 17, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction17.jpg', 'title16', 'content16', 'CLOTHING', 'BEST', 'CLOSE', 1000, 1, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction18.jpg', 'title17', 'content17', 'CLOTHING', 'GOOD', 'CLOSE', 2000, 2, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction19.jpg', 'title18', 'content18', 'CLOTHING', 'NORMAL', 'CLOSE', 3000, 3, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction20.jpg', 'title19', 'content19', 'CLOTHING', 'WORST', 'CLOSE', 4000, 4, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction21.jpg', 'title20', 'content20', 'CLOTHING', 'BEST', 'CLOSE', 5000, 5, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction22.jpg', 'title21', 'content21', 'CLOTHING', 'GOOD', 'CLOSE', 6000, 6, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction23.jpg', 'title22', 'content22', 'CLOTHING', 'NORMAL', 'CLOSE', 7000, 7, now(),
        date_add(now(), interval 1 month), now()),
       (1, 'auction24.jpg', 'title23', 'content23', 'CLOTHING', 'WORST', 'CLOSE', 8000, 8, now(),
        date_add(now(), interval 1 month), now());

insert into bidding_history(member_id, auction_id, price, is_pay, success_bid_at, created_at)
values (2, 17, 1000, true, now(), now()),
       (1, 2, 500, false, null, now()),
       (1, 2, 700, false, null, now()),
       (1, 2, 1000, false, now(), now()),
       (1, 3, 3000, true, now(), now()),
       (1, 4, 3000, false, now(), now()),
       (1, 5, 3000, true, now(), now()),
       (1, 7, 5000, false, now(), now()),
       (1, 8, 5000, true, now(), now()),
       (1, 9, 5000, true, now(), now()),
       (1, 10, 5000, true, now(), now());

insert into auction_reviews(member_id, auction_id, rating, content, created_at)
values (1, 2, 3, 'good', now()),
       (2, 3, 2, '.', now()),
       (3, 4, 1, '좋음', now()),
       (4, 1, 5, '', now());
